import Head from "next/head";
import Header from "../components/Header";
import VideoFeed from "../components/VideoFeed";

export default function Home() {
  return (
    <div className="w-full h-screen flex flex-col">
      <Head>
        <title>TikTok Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://th.bing.com/th/id/R.67bc88bb600a54112e8a669a30121273?rik=vsc22vMfmcSGfg&pid=ImgRaw&r=0" />
      </Head>

      {/* ✅ Only show the logo now */}
      <Header />

      {/* ✅ Ensure VideoFeed has some margin at the top */}
      <div className="w-full flex-1 mt-2">
        <VideoFeed />
      </div>
    </div>
  );
}
